name: "Terraform Plan"
description: "Runs Terraform Plan against a specific AWS account."

inputs: 
  environment: 
    description: "Target Environment"
    required: true
  environment-config-file: 
    description: "Location of config file describing tf backend relative to terraform root"
    required: true
  variable-file: 
    description: "Location of variables for the environment"
    required: true
  terraform-root: 
    description: "Directory containing the terraform configuration files"
    required: true


runs: 
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Verify Keys
        shell: bash
        run: aws sts get-caller-identity --debug 
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.13.5

      - name: Terraform Init
        shell: bash
        run : |
          terraform \
            -chdir=${{ inputs.terraform-root }} \
            init \
            -backend-config=${{ inputs.environment-config-file }} \
            

      - name: Terraform Validate
        shell: bash
        run: terraform validate
      
      - name: Terraform Plan
        shell: bash
        run: |
          terraform \
          -chdir=${{ inputs.terraform-root }} \
          plan \
          -out=tfplan-${{ inputs.environment }} \
          -var-file=${{ inputs.variable-file }} \
      
      - name: Show Plan Summary
        shell: bash
        run: terraform -chdir=${{ inputs.terraform-root }} show -no-color tfplan-${{ inputs.environment }}
