name: "Terraform Plan"
description: "Runs Terraform Plan against a specific AWS account."

inputs: 
  environment: 
    description: "Target Environment"
    required: true
  aws-region: 
    description: "Target AWS Regions"
    default: "mx-central-1"
  aws-account:
    description: "Account number for target environment"
    required: true
  environment-config-file: 
    description: "Location of config file describing tf backend"
    required: true


runs: 
  using: "composite"
  steps:
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/Terraform-Runner
          aws-region: ${{ inputs.aws-region }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.13.5

      - name: Terraform Init
        shell: bash
        run : |
          terraform init \
            -backend-config=${{ inputs.environment-config-file }}
      
      - name: Terraform Validate
        shell: bash
        run: terraform validate
      
      - name: Terraform Plan
        shell: bash
        run: terraform plan -out=tfplan-${{ inputs.environment }}
      
      - name: Show Plan Summary
        shell: bash
        run: terraform show -no-color tfplan-${{ inputs.environment }}